version: "3.7"
services:
  db:
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    build:
      context: "."
      dockerfile: "Dockerfile.db"
    ports:
    - "3306:3306"
  web:
    environment:
      - APP_ENV=dev
    build:
      context: "."
      dockerfile: "Dockerfile.web"
    ports:
    - "8000:80"
    volumes:
    - ./app:/opt/asisto/app
    - ./bin:/opt/asisto/bin
    - ./data:/opt/asisto/data
    - ./libs:/opt/asisto/libs
    - ./log:/opt/asisto/log
    - ./www:/opt/asisto/www
    depends_on:
      - "db"
    links:
      - "db:mysql"
