# https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html
FROM webdevops/php-nginx:7.2

WORKDIR /opt/asisto
ENV WEB_DOCUMENT_ROOT=/opt/asisto/www

RUN apt update

RUN mkdir -p /usr/share/man/man1
RUN apt install -y pandoc libpng-dev default-jre

RUN apt install -y --no-install-recommends --no-install-suggests libreoffice

# in order to get mails working
RUN apt install -y --no-install-recommends --no-install-suggests mailutils sendmail
RUN chsh -s /bin/bash www-data

# Install dependencies
COPY composer.* ./
RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader && rm -rf /root/.composer

RUN mkdir /opt/asisto/temp
RUN chmod 777 -R /opt/asisto/temp

# enable mpdf tmp folder
RUN chmod 777 -R /opt/asisto/vendor/mpdf/mpdf

# Finish composer
RUN composer dump-autoload --no-scripts --no-dev --optimize
