FROM mysql:5.5

ENV MYSQL_DATABASE=web \
    MYSQL_ROOT_PASSWORD=test_env \
    MYSQL_USER=root

ADD sql/db_structure_with_basic_data.sql /docker-entrypoint-initdb.d

ADD sql/init.sh /docker-entrypoint-initdb.d